import { installCapture, enterFullscreen } from '../tests/helpers/capture.ts';
import { chromium, expect } from '@playwright/test';
import { mkdir } from 'node:fs/promises';

const baseURL = process.env.BURNHOP_PREVIEW_URL ?? 'http://127.0.0.1:4173';
const browser = await chromium.launch();
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, deviceScaleFactor: 2 });
  const errors = [], remoteRequests = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  page.on('request', request => { if (/^https?:/.test(request.url()) && !request.url().startsWith(`${baseURL}/`)) remoteRequests.push(request.url()); });
  await installCapture(page);
  await page.goto(baseURL);
  await enterFullscreen(page);
  await page.getByRole('button', { name: 'Customize', exact: true }).click();
  const category = name => page.getByRole('navigation', { name: 'Character categories' }).getByRole('button', { name, exact: true });
  const stored = () => page.evaluate(() => JSON.parse(localStorage.getItem('burnhop-settings')));
  await category('Hair').click();
  await page.getByRole('button', { name: 'Spiky', exact: true }).click();
  await page.getByRole('button', { name: 'Hair colour: White', exact: true }).click();
  await category('Headgear').click();
  await page.getByRole('button', { name: 'None', exact: true }).click();
  const look = (await stored()).appearance;
  await page.getByRole('button', { name: 'Keep this look', exact: true }).click();
  await page.getByLabel('Name this look', { exact: true }).fill('Outpost night');
  await page.getByRole('button', { name: 'Save new look', exact: true }).click();
  await category('Hair').click();
  await page.getByRole('button', { name: 'Buzz cut', exact: true }).click();
  await category('Saved looks').click();
  await page.getByRole('button', { name: 'Apply Outpost night', exact: true }).click();
  expect((await stored()).appearance).toEqual(look);
  await mkdir('docs/screenshots', { recursive: true });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: 'docs/screenshots/47-creator-production.png', fullPage: true });
  await page.setViewportSize({ width: 320, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.screenshot({ path: 'docs/screenshots/47-creator-production-mobile.png', fullPage: true });
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.reload();
  await enterFullscreen(page);
  expect((await stored()).appearance).toEqual(look);
  expect((await stored()).savedLooks[0].appearance).toEqual(look);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Enter practice', exact: true }).click();
  await expect(page.getByTestId('fps')).toHaveText(/^\d+ FPS$/);
  await page.screenshot({ path: 'docs/screenshots/47-custom-pilot-production.png' });
  expect(await page.evaluate(() => window.__BURNHOP__)).toBeUndefined();
  expect(errors).toEqual([]); expect(remoteRequests).toEqual([]);
  console.log('Production creator passed: live edits, independent colour, saved snapshot/restore/reload, 320px layout, practice entry, zero errors/external requests/development diagnostics.');
} finally { await browser.close(); }
